# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  release:
    needs: build  # This job depends on the successful completion of build-and-test
    permissions: write-all
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Install xml tools
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet
      - name: Get Mod Version
        run: |
          mod_version=$(xml xpath '//ModVer/text()' ModInfo.xml)
          echo "Mod Version: $mod_version"
          echo "::set-output name=mod_version::$mod_version"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_mod_version.outputs.mod_version }}
          release_name: Release ${{ github.sha }}
          body: ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload DLL
        uses: actions/upload-artifact@v3
        with:
          name: AGMLIB.dll
          path: C:\Program Files (x86)\Steam\steamapps\common\Nebulous\Mods\AGMLIB\Debug\net481\AGMLIB.dll
